# Generated by Django 3.1.3 on 2020-11-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
